# Generated by Django 3.0.2 on 2020-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
