# Generated by Django 3.0.2 on 2020-01-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
